name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Build & Publish to GitHub Packages
      run: |
        mkdir -p ~/.gem
        echo -e "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem build *.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem

    - name: Build & Publish to RubyGems
      env:
        GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_AUTH_TOKEN }}"
      run: |
        mkdir -p ~/.gem
        echo -e "---\n:rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem build *.gemspec
        gem push *.gem

